type AgentRole = "orchestrator" | "habitat" | "scientist" | "guardian" | "adventurer";

interface RunJsonAgentOptions {
  role: AgentRole;
  task: string;
  context: unknown;
  fallback: Record<string, unknown>;
}

const DEFAULT_MODEL = "gpt-4.1-mini";

const AGENTS: Record<AgentRole, { name: string; instructions: string }> = {
  orchestrator: {
    name: "Rootine OrquestradorIA",
    instructions: `You are Rootine's AI orchestrator. You mediate between specialist agents and Supabase data.
Decide how the user's context should be interpreted, preserve database contracts, and return only valid JSON.`,
  },
  habitat: {
    name: "Rootine Agente Habitat",
    instructions: `You are the Habitat specialist. You give the Rootine tree its personality.
The tree speaks in Brazilian Portuguese with an epic, ancestral, cultured, respectful voice, like a wise elder.
You never chat directly with the user. Generate short clickable leaf messages grounded in the user's history.`,
  },
  scientist: {
    name: "Rootine Agente Cientista",
    instructions: `You are the Profile Scientist. You synthesize user behavior into useful, practical guidance.
You can chat directly with the user in Brazilian Portuguese. Prefer day-to-day protocols based on past app interactions.
When updating profile intelligence, be conservative, preserve existing evidence, and return structured JSON.`,
  },
  guardian: {
    name: "Rootine Agente Guardião",
    instructions: `You are the Trail Guardian. You generate educational quizzes for Rootine's Trilha.
Never create flashcards. Flashcards are stored in the database and are not generated by agents.
Quizzes must be concise, practical, and based on the user's sustainability journey.`,
  },
  adventurer: {
    name: "Rootine Agente Aventureiro",
    instructions: `You are the Adventure specialist. You generate daily and specialized sustainability missions.
You do not chat directly with the user. Missions must be actionable, accessible, personalized, and written in Brazilian Portuguese.`,
  },
};

export const allowedCategories = [
  "waste",
  "energy",
  "water",
  "transport",
  "food",
  "consumption",
] as const;

export function extractStringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string")
    : [];
}

export function clampAffinities(value: Record<string, unknown> = {}) {
  const affinities: Record<string, number> = {};

  for (const category of Object.keys(value)) {
    if (!allowedCategories.includes(category as any)) continue;

    const numeric = Number(value[category]);
    if (!Number.isNaN(numeric)) {
      affinities[category] = Math.min(1, Math.max(-1, numeric));
    }
  }

  return affinities;
}

export function parseJsonObject<T extends Record<string, unknown>>(
  raw: string,
  fallback: T,
): T {
  try {
    const trimmed = raw.trim();
    const jsonStart = trimmed.indexOf("{");
    const jsonEnd = trimmed.lastIndexOf("}");
    const json = jsonStart >= 0 && jsonEnd >= jsonStart
      ? trimmed.slice(jsonStart, jsonEnd + 1)
      : trimmed;

    const parsed = JSON.parse(json);
    return parsed && typeof parsed === "object" ? parsed : fallback;
  } catch (error) {
    console.error("[AGENTS] JSON parse failed:", error);
    return fallback;
  }
}

export async function runJsonAgent<T extends Record<string, unknown>>({
  role,
  task,
  context,
  fallback,
}: RunJsonAgentOptions): Promise<T> {
  try {
    const raw = await runAgentText(role, `${task}

CONTEXT:
${JSON.stringify(context, null, 2)}

Return STRICTLY valid JSON. Do not wrap it in markdown.`);

    return parseJsonObject<T>(raw, fallback as T);
  } catch (error) {
    console.warn(`[AGENTS] ${role} failed; using fallback output:`, error);
    return fallback as T;
  }
}

async function runAgentText(role: AgentRole, input: string): Promise<string> {
  const apiKey = Deno.env.get("OPENAI_API_KEY") ?? Deno.env.get("OPEN_AI_KEY");
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY ou OPEN_AI_KEY não configurada.");
  }

  try {
    return await runAgentSdk(role, input, apiKey);
  } catch (error) {
    console.warn("[AGENTS] SDK unavailable, falling back to HTTP:", error);
    return await runAgentHttp(role, input, apiKey);
  }
}

async function runAgentSdk(role: AgentRole, input: string, apiKey: string) {
  const agentsSdk = await import("npm:@openai/agents@0.11.4");
  const model = Deno.env.get("OPENAI_MODEL") ?? DEFAULT_MODEL;
  const config = AGENTS[role];

  if (typeof agentsSdk.setDefaultOpenAIKey === "function") {
    agentsSdk.setDefaultOpenAIKey(apiKey);
  }

  const agent = new agentsSdk.Agent({
    name: config.name,
    model,
    instructions: config.instructions,
  });

  const result = await agentsSdk.run(agent, input);
  return String(result.finalOutput ?? "");
}

async function runAgentHttp(role: AgentRole, input: string, apiKey: string) {
  const model = Deno.env.get("OPENAI_MODEL") ?? DEFAULT_MODEL;
  const config = AGENTS[role];

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: config.instructions },
        { role: "user", content: input },
      ],
      response_format: { type: "json_object" },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Erro OpenAI: ${response.status} - ${errorText}`);
  }

  const data = await response.json();
  return String(data.choices?.[0]?.message?.content ?? "");
}

export async function logAgentInteraction(
  supabaseAdmin: any,
  payload: {
    userId: string;
    agent: AgentRole;
    eventType: string;
    inputSummary: Record<string, unknown>;
    output: Record<string, unknown>;
    status?: "success" | "error";
    errorMessage?: string;
  },
) {
  try {
    await supabaseAdmin.from("agent_interactions").insert({
      user_id: payload.userId,
      agent: payload.agent,
      event_type: payload.eventType,
      input_summary: payload.inputSummary,
      output: payload.output,
      status: payload.status ?? "success",
      error_message: payload.errorMessage ?? null,
    });
  } catch (error) {
    console.warn("[AGENTS] Failed to log interaction:", error);
  }
}
